#!/usr/bin/env bash
build_container() {
    BASE_DIR=${1}
    CONTAINER_NAME=${2}
    USERNAME=${3}
    CONTAINER_BUILD_PATH=${BASE_DIR}/${CONTAINER_NAME}
    BUILD_COMMAND="docker build -t ${USERNAME}/tidepool-${CONTAINER_NAME} \
        ${CONTAINER_BUILD_PATH}"
    echo
    echo "Running build command:"
    echo ${BUILD_COMMAND}
    echo
    ${BUILD_COMMAND}
}

BASE_DIR=${1}
USERNAME=${2}

#for container_name in $(cat "${BASE_DIR}/container_names.txt"); do
CONTAINER_NAMES="common node go styx gatekeeper seagull shoreline jellyfish"
for container_name in ${CONTAINER_NAMES}; do
    build_container ${BASE_DIR} $container_name ${USERNAME}

    if [ "$?" != "0" ]; then
        break
    fi
done
